### ISSUE TITLE
I like your app.. check this large Angular 2 App

### ISSUE THREAD

**Issue by born2net** [mattlewis92/angular2-tv-tracker#2]
Thanks for a great article... I just posted a massive Angular 2 bootstrap project. Anyone interested om Angular 2 will love it. Check out the working demo @ http://ng2.javascriptninja.io and source at: https://github.com/born2net/ng2Boilerplate

regards

Sean.

**Comment by mattlewis92** [comment]
Hi, I saw this on twitter the other day, it looks really good! One piece of feedback I'd give though is not to check in the built JS / sourcemaps to the repo as it makes navigating the source quite difficult.

**Comment by born2net** [comment]
tx for the comment, I did it only because I had to make some changes to the types to remove dup errors so people can get that effort, but yes once all the kinks are cleaned from Angular team, tsd should suffice.

fyi I will incorporate your | async pipe to my app as well ;)

regards
