### ISSUE TITLE
can you please explain selector: 'th[sortableHeader]',

### ISSUE THREAD

**Issue by born2net** [mattlewis92/angular2-tv-tracker#3]
trying to understand why you are using

```selector: 'th[sortableHeader]',```

in your table header selector instead of just 'th'?

tx again

Sean

**Comment by mattlewis92** [comment]
I only want the directive to apply to `th` elements with the attribute `sortableHeader`. Using `th` would mean it would apply to all `th` elements which I don't want as not all table headers are sortable. Hope that helps :smile:

**Comment by born2net** [comment]
got it... tx for that
