### ISSUE TITLE
 webpack-dev-server --progress Error

### ISSUE THREAD

**Issue by jchri853** [mattlewis92/angular2-tv-tracker#4]
Getting the following error building the app any ideas? (Attached is the log file)

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.3
3 info using node@v4.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-tv-tracker@~prestart: angular2-tv-tracker@
6 silly lifecycle angular2-tv-tracker@~prestart: no script for prestart, continuing
7 info lifecycle angular2-tv-tracker@~start: angular2-tv-tracker@
8 verbose lifecycle angular2-tv-tracker@~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-tv-tracker@~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/user/Downloads/angular2-tv-tracker-master 2/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10 verbose lifecycle angular2-tv-tracker@~start: CWD: /Users/user/Downloads/angular2-tv-tracker-master 2
11 silly lifecycle angular2-tv-tracker@~start: Args: [ '-c', 'webpack-dev-server --progress' ]
12 silly lifecycle angular2-tv-tracker@~start: Returned: code: 1  signal: null
13 info lifecycle angular2-tv-tracker@~start: Failed to exec start script
14 verbose stack Error: angular2-tv-tracker@ start: `webpack-dev-server --progress`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:817:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-tv-tracker@
16 verbose cwd /Users/user/Downloads/angular2-tv-tracker-master 2
17 error Darwin 15.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v4.1.0
20 error npm  v3.3.3
21 error code ELIFECYCLE
22 error angular2-tv-tracker@ start: `webpack-dev-server --progress`
22 error Exit status 1
23 error Failed at the angular2-tv-tracker@ start script 'webpack-dev-server --progress'.
23 error This is most likely a problem with the angular2-tv-tracker package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --progress
23 error You can get their info via:
23 error     npm owner ls angular2-tv-tracker
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mattlewis92** [comment]
I've never seen this before, maybe try upgrading npm to the latest version and then delete and reinstall npm dependencies from scratch, as I think that version of npm was really buggy
