### ISSUE TITLE
Using SCSS in components

### ISSUE THREAD

**Issue by vchnazarov** [mattlewis92/angular2-tv-tracker#5]
I'm trying to include SCSS in components, e.g.:
`@Component({
..., styleUrls: ['styles/app.scss']
})`
But the .scss files don't transform into valid css code: [http://i.imgur.com/OhjfFu5.png](url)
How to include SCSS in components properly?

**Comment by mattlewis92** [comment]
Angular2 doesn't support sass, only CSS. You can work around it with webpack like this: https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components

**Comment by vchnazarov** [comment]
When I try to compile application I get the error
`Module not found: Error: Cannot resolve 'file' or 'directory' ....`

Thank you, will be trying to figure it out.

**Comment by mattlewis92** [comment]
If you're using `styles/app.scss` as in your example you should prefix it with ./ like so: `./styles/app.scss`, otherwise webpack will try and resolve a module in `node_modules/styles/app.scss` hence the not found error 😄
